apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: asia-southeast1-docker.pkg.dev/fluent-grammar-408618/englishbuddydeployment/react-admin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6060
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://backend-service:5050"
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
          limits:
            memory: "1Gi"
            cpu: "1000m"