apiVersion: v1
kind: Service
metadata:
  name: machine-learning-service
spec:
  type: LoadBalancer
  selector:
    app: machinelearning
  ports:
    - protocol: TCP
      port: 6090
      targetPort: 6090

